# Generated by Django 5.1 on 2024-08-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_fabric_product_length_product_neck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
