# Generated by Django 5.1 on 2024-08-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_skus', to='products.product'),
        ),
    ]
